collection_name: dbpedia_float32_noquant # float32 base dtype, no quantization (baseline)
data:
  # do not change data path -- vectors are computed server-side via Qdrant Cloud Inference
  corpus:
    path: ../../data/dbpedia/corpus.jsonl
dense_vectors:
  dtype: float32
  memory: cached
colbert_vectors:
  dtype: float32
  memory: cached
  multivector_config:
    comparator: max_sim
  hnsw_config:
    m: 0 # indexing should be disabled since we are using these for rescoring (otherwise very expensive)
sparse_vectors:
  modifier: idf
